backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: content/assets
public_folder: assets
collections:
  - name: blog
    slug: 'index'
    preview_path: 'blog/index'
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - name: projects
    preview_path: "projects"
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }